# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageURL',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
